// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/add_versions": {
            "post": {
                "description": "添加新的版本号信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本管理"
                ],
                "summary": "添加版本号信息",
                "parameters": [
                    {
                        "description": "版本号信息",
                        "name": "version",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Version"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功消息"
                    },
                    "400": {
                        "description": "请求错误"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/delete_versions/{id}": {
            "delete": {
                "description": "根据ID删除版本号信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本管理"
                ],
                "summary": "删除版本号信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本号ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功消息"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/get_versions/{id}": {
            "get": {
                "description": "根据ID获取版本号信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本管理"
                ],
                "summary": "根据ID获取版本号信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本号ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Version"
                        }
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/join_raft_cluster/": {
            "get": {
                "description": "此接口用于将当前节点加入到Raft集群中。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "集群管理"
                ],
                "summary": "向领导者节点发送请求，把自身加入到集群中",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点ID",
                        "name": "ID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "节点地址",
                        "name": "Address",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功消息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/update_versions/{id}": {
            "put": {
                "description": "根据ID更新版本号信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本管理"
                ],
                "summary": "更新版本号信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本号ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "版本号信息",
                        "name": "version",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Version"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功消息"
                    },
                    "400": {
                        "description": "请求错误"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Version": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "versionNo": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
